
language: node_js
node_js:
  - '8'
  - '10'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) -t 0135d48d-0bf3-41e9-a61a-ae66d82ece6e
